function [DataStruct] = AddEngineThrust(DataStruct)
% AddEngineThrust.m is a script which adds the engine thrust to the data
% structure.
%
% Inputs:   
%           DataStruct: data structure without engine thrust
%
% Outputs:  
%           DataStruct: data structure with engine thrust
%
% Made by: M.A. van den Hoek & L.J. van Horssen, September 2016 - Version 1.0
%% Calculate the engine thrust and store it into the data structure
% Load engine data look-up tables. Inputs are Mach number and N1 speed, the
% output is the thrust generated by the engine
load('jt15data')

% Obtain the fan speed of both left and right engine
N1_l = DataStruct.Engine.lh.N1.data;
N1_r = DataStruct.Engine.rh.N1.data;

% Obtain the sound of speed from the standard atmosphere model
[~, a, ~, ~] = atmosisa(-DataStruct.State.z.data);

% Obtain the true airspeed
Vtas = DataStruct.Measurement.Vtas.reconstructed;

% Calculate the Mach number
Mach = Vtas./a;

% Calculate the thrust output of both the left and right engine. The output
% is given in lbs
Thrust_l = interp2(matthr(2:12,1),matthr(1,2:6),matthr(2:12,2:6)',N1_l,Mach);
Thrust_r = interp2(matthr(2:12,1),matthr(1,2:6),matthr(2:12,2:6)',N1_r,Mach);

% Convert lbs output to Newton 
Thrust_l = Thrust_l*4.44822162825; % Convert lbs to Newton
Thrust_r = Thrust_r*4.44822162825; % Convert lbs to Newton

% Add the thrust of both the left and the right engine
Thrust = Thrust_l + Thrust_r; % Two engines

% Add the engine thrust to the data structure
DataStruct.Engine.Thrust.data = Thrust;